python:
   version: 3.8
   install:
      - method: pip
        path: .
        extra_requirements:
            - docs
      - method: pip
        path: --editable ".[tests]"
   system_packages: true
